version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: openschema-redis
    ports:
      - "6379:6379"
    networks:
      - openschema-network

  postgres:
    image: postgres:latest
    container_name: openschema-postgres
    environment:
      POSTGRES_DB: openschema
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openschema-network

  mongo:
    image: mongo:latest
    container_name: openschema-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - openschema-network

networks:
  openschema-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
